plugins {
    id 'com.adarshr.test-logger' version '4.0.0'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
    id 'org.ajoberstar.grgit' version '5.2.1'
    id 'org.sonarqube' version '4.4.1.3373'
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'application'
apply plugin: "jacoco"
apply plugin: "com.github.johnrengelman.shadow"


sonarqube {
    properties {
        property "sonar.host.url", "http://localhost:9000"
        property "sonar.projectKey", "org.sonarqube:cvs-svc-doc-gen"
        property "sonar.projectName", "cvs-svc-doc-gen"
        property "sonar.projectVersion", "1.0"
        property "sonar.sourceEncoding", "UTF-8"
    }
}

group 'uk.dvsa.mot'
version "${version}"

mainClassName = "uk.dvsa.mot.PdfGenerator"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

jacoco {
    toolVersion = "0.8.11"
}

jacocoTestReport {
    group = "Reporting"
    reports {
        xml.required = true
        csv.required = false
        html.outputLocation = file("${buildDir}/reports/coverage")
        // html.destination file("./reports/coverage")
    }
}


testlogger {
    theme 'mocha'
    showExceptions true
    showStackTraces true
    showFullStackTraces false
    showCauses true
    slowThreshold 2000
    showSummary true
    showSimpleNames false
    showPassed true
    showSkipped true
    showFailed true
    showStandardStreams false
    showPassedStandardStreams false
    showSkippedStandardStreams false
    showFailedStandardStreams true
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

repositories {
   mavenCentral()
}

dependencies {
    implementation group: 'com.amazonaws', name: 'aws-lambda-java-core', version: '1.1.0'
    implementation group: "com.github.jknack", name: "handlebars", version: "4.5.0"
    implementation group: 'org.xhtmlrenderer', name: 'flying-saucer-pdf-openpdf', version: '9.1.20'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.15.0'
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.15.0'
    implementation group: 'com.amazonaws', name: 'aws-lambda-java-log4j2', version: '1.5.1'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.22.1'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.22.1'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.22.1'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.4'
    implementation fileTree(dir: 'jars', include: '*.jar')
    testImplementation group: 'junit', name: 'junit', version: '4.13.1'
    testImplementation group: 'org.jsoup', name: 'jsoup', version: '1.15.3'
    testImplementation group: 'commons-io', name: 'commons-io', version: '2.14.0'
    testImplementation group: 'com.itextpdf', name: 'itextpdf', version: '5.5.12'
}

task buildZip(type: Zip) {
    from compileJava
    from processResources
    into('lib') {
        from configurations.runtimeClasspath
    }
}

task buildManifest(type: Copy) {
    from 'src/main/filteredResources'
    into 'build/resources/main'

    def branchName =  project.findProperty('branchName') ?: grgit.branch.current().getName()
    def commitId = project.findProperty('commitId') ?: grgit.head().getId()
    println "Commit id: " + commitId
    println "Branch name: " + branchName

    expand(gitCommitId: commitId, gitBranch: branchName)
}

tasks.test {
    environment "LAMBDA_TASK_ROOT", "./src/main/resources"
}

tasks.compileTestJava {
    dependsOn buildManifest
}

buildZip.dependsOn buildManifest
build.dependsOn buildZip
