package uk.gov.dvsa.enums;

public enum CertificateTypes {

    PASS("MOT/VT20"),
    FAIL("MOT/VT30"),
    WELSH_PASS("MOT/VT20W"),
    WELSH_FAIL("MOT/VT30W"),
    PRS("MOT/PRS"),
    WELSH_PRS("MOT/PRSW"),

    EU_CONTINGENCY_PASS("MOT/EU_CT20"),
    EU_CONTINGENCY_FAIL("MOT/EU_CT30"),

    CONTINGENCY_PASS("MOT/CT20"),
    CONTINGENCY_FAIL("MOT/CT30"),
    CONTINGENCY_ADVISORY_NOTICE("MOT/CT32"),

    ADVISORY_NOTICE("MOT/VT32VE"),
    WELSH_ADVISORY_NOTICE("MOT/VT32VEW"),
    COMPLIANCE_ADVISORY_NOTICE("MOT/EU_VT32VE"),
    COMPLIANCE_WELSH_ADVISORY_NOTICE("MOT/EU_VT32VEW"),

    VT29("MOT/VT29"),

    CVS_PASS("CVS/VTP20"),
    CVS_PASS_WELSH("CVS/VTP20W"),
    CVS_PASS_BILINGUAL("CVS/VTP20_BILINGUAL"),
    CVS_FAIL("CVS/VTP30"),
    CVS_FAIL_WELSH("CVS/VTP30W"),
    CVS_FAIL_BILINGUAL("CVS/VTP30_BILINGUAL"),
    CVS_PSV_PRS("CVS/PSV_PRS"),

    CVS_HGV_PASS("CVS/VTG5"),
    CVS_HGV_PASS_WELSH("CVS/VTG5W"),
    CVS_HGV_PASS_BILINGUAL("CVS/VTG5_BILINGUAL"),
    CVS_TRL_PASS("CVS/VTG5A"),
    CVS_TRL_PASS_WELSH("CVS/VTG5AW"),
    CVS_TRL_PASS_BILINGUAL("CVS/VTG5A_BILINGUAL"),
    CVS_HGV_TRL_FAIL("CVS/VTG30"),
    CVS_HGV_TRL_FAIL_WELSH("CVS/VTG30W"),
    CVS_HGV_TRL_FAIL_BILINGUAL("CVS/VTG30_BILINGUAL"),
    CVS_HGV_PRS("CVS/HGV_PRS"),
    CVS_HGV_PRS_BILINGUAL("CVS/HGV_PRS_BILINGUAL"),
    CVS_TRL_PRS("CVS/TRL_PRS"),
    CVS_TRL_PRS_BILINGUAL("CVS/TRL_PRS_BILINGUAL"),
    RWT_DATA("CVS/RWT"),
    ADR_PASS("CVS/ADR_PASS"),
    VTG6_VTG7("CVS/VTG6_VTG7"),

    TRAILER_INTO_SERVICE("CVS/TrailerIntoService"),

    INSPECTION_CHECKLIST("MOT/InspectionChecklist"),

    IVA30("CVS/IVA30"),

    MSVA30("CVS/MSVA30");

    private final String certificateType;

    CertificateTypes(String certificateType) {
        this.certificateType = certificateType;
    }

    public String getCertificateType() {
        return certificateType;
    }
}
